mentees/urls.py
from django.urls import path
from . import views

app_name='mentees'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('dashboard/', views.DashBoard.as_view(), name='dashboard'),
     path('profile/', views.Profile.as_view(), name='profile'),
]

mentors/urls.py
from django.urls import path
from . import views

app_name = 'mentors'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('dashboard/', views.DashBoard.as_view(), name='dashboard'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('dashboard/project/new',
         views.CreateProject.as_view(), name='create_project'),
    path('dashboard/project/edit/<int:pk>',
         views.EditProject.as_view(), name='edit_project'),
    path('<int:pk>/', views.ProjectDetails.as_view(), name='details'),
]

projects/urls.py
from django.urls import path
from . import views

app_name='projects'

urlpatterns = [
    path('index/', views.Index.as_view(), name='project_index'),
    path('<int:pk>/', views.ProjectDetail.as_view(), name='detail'),
    path('code_of_conduct/', views.conduct, name='conduct'),
    path('psoc2020/', views.psoc2020, name='psoc2020'),
]

soc/urls.py
from django.contrib import admin
from django.urls import path, include

import projects.views as project_views
import mentors.views as mentor_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', project_views.Main.as_view(), name='main_page'),
    path('adminpanel/', project_views.AdminIndex.as_view(), name='admin_panel'),
    path('adminpanel/<int:pk>/', project_views.AdminProjectDetail.as_view(),
         name='admin_panel_project_detail'),
    path('login/', mentor_views.Login.as_view(), name='user_login'),
    path('logout/', mentor_views.LogOut.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('mentors/', include('mentors.urls')),
    path('projects/', include('projects.urls')),
    path('mentees/', include('mentees.urls')),
    path('terms', mentor_views.Terms.as_view(), name='terms')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mentors/models.py
from django.db import models
from django.contrib.auth.models import User

#model class for mentor.

def user_directory_path(instance, filename):
    return '{0}/{1}'.format(instance.user.username, filename)

class Mentor(models.Model):
    name = models.CharField(max_length=64, default="")
    linkedin = models.CharField(max_length=100, null=True, default="")
    github = models.CharField(max_length=100, null=True, default="")
    # cv = models.FileField(upload_to=user_directory_path, null=True, blank=True)
    cv = models.CharField(max_length=300, null=True, default="")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_mentor = models.BooleanField(default=True)

    def __str__(self):
        return self.name

projects/models.py
from django.db import models

from mentors.models import Mentor

#model class for project
class Project(models.Model):
    title = models.CharField(max_length=80, default='')
    description = models.TextField(default='')
    code = models.CharField(max_length=8, default='')
    stack = models.CharField(max_length=100, default='')
    mentor = models.ForeignKey(Mentor, on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.title

mentors/forms.py
from django.forms import ModelForm, CharField, PasswordInput 
from django.contrib.auth.models import User

from .models import Mentor

class UserForm(ModelForm):
    password = CharField(widget=PasswordInput())
    class Meta():
        model = User
        fields = ['username', 'password', 'email']

class MentorForm(ModelForm):
    class Meta():
        model = Mentor
        fields = ['name', 'linkedin', 'cv']

mentors/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages

from .models import User, Mentor
from projects.models import Project
from mentees.models import Mentee
from .forms import MentorForm, UserForm
from projects.forms import ProjectForm

# view to handle the registration form for mentors


class Register(View):
    form_class = UserForm
    registered = False
    template_name = 'mentors/register.html'
    errors = []

    def get(self, request, *args, **kwargs):
        self.errors = []
        return render(request, self.template_name, {'registered': self.registered})

    def post(self, request, *args, **kwargs):
        data = {
            'username': request.POST.get('username'),
            'email': request.POST.get('email'),
            'password': request.POST.get('password')
        }
        self.errors = []
        form = self.form_class(data=data)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()

            mentor = Mentor(user=user)
            mentor.save()

            self.registered = True
        else:
            self.errors.append(form.errors)
        return render(request, self.template_name, {'form': form, 'registered': self.registered, 'errors': self.errors})


# view to handle login
class Login(View):
    template_name = 'mentors/login.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = authenticate(username=username, password=password)
        except:
            messages.add_message(request, messages.ERROR,
                                 'Invalid Username or Password')

        if user:
            if user.is_active:
                login(request, user)
                if hasattr(request.user, 'mentor'):
                    return HttpResponseRedirect(reverse('mentors:dashboard'))
                elif hasattr(request.user, 'mentee'):
                    return HttpResponseRedirect(reverse('mentees:dashboard'))
                else:
                    messages.add_message(
                        request, messages.ERROR, 'You are Admin')
            else:
                messages.add_message(
                    request, messages.ERROR, 'Your Account was Inactive')
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            messages.add_message(request, messages.ERROR,
                                 'Invalid Username or Password')
        return render(request, self.template_name)


# view to handle logout of users
class LogOut(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('main_page'))


# view to handle the dashboard of mentors
class DashBoard(View):
    template_name = 'mentors/dashboard.html'
    show_button = True

    def get(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentor'):
            if not ((request.user.mentor.name != "") and (request.user.mentor.linkedin != "" or request.user.mentor.cv != "")):
                return redirect('mentors:profile')
            else:
                if (request.user.mentor.project_set.all().count() >= 3):
                    self.show_button = False
                return render(request, 'mentors/dashboard.html', {'show_button': self.show_button})
        else:
            return HttpResponse("You are not a mentor")

    def post(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentor'):
            project_id = request.POST.get('project')
            project = Project.objects.get(pk=project_id)

            pk = request.POST.get('mentee_id')
            mentee = Mentee.objects.get(pk=pk)

            if mentee.selected == None:
                mentee.selected = project
                mentee.save()
                return HttpResponseRedirect(reverse('projects:detail', args=(project_id,)))

            else:
                return HttpResponse('This mentee is already selected for another project.')
        else:
            return HttpResponse("You are not a mentor")


# view to handle profile section of mentor
class Profile(View):
    template_name = 'mentors/profile.html'
    form_class = MentorForm

    def get(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentor'):
            mentor = request.user.mentor
            data = {
                'name': mentor.name,
                'linkedin': mentor.linkedin,
                'github': mentor.github,
            }
            if mentor.cv == "":
                data['display'] = 'block'
            else:
                data['display'] = 'none'
            return render(request, 'mentors/profile.html', {'data': data})
        else:
            return HttpResponse("You are not a mentor.")

    def post(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentor'):
            mentor = request.user.mentor
            name = request.POST.get('name')
            linkedin = request.POST.get('linkedin')
            github = request.POST.get('github')
            cv = request.POST.get('CV')
            # if mentor.cv == "":
            # cv = request.FILES['CV']

            mentor.name = name
            mentor.linkedin = linkedin
            mentor.github = github
            mentor.cv = cv
            # if mentor.cv == "":
            # mentor.cv = cv
            mentor.save()
            return HttpResponseRedirect(reverse('mentors:dashboard'))
        else:
            return HttpResponse("You are not a mentor.")


# implemented the view to create a new project by a mentor
class CreateProject(View):
    template_name = 'mentors/create_project.html'
    form_class = ProjectForm

    def get(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentor'):
            return render(request, 'mentors/create_project.html')
        else:
            return HttpResponse("You are not a mentor")

    def post(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentor'):
            title = request.POST.get('title')
            description = request.POST.get('description')
            stack = request.POST.get('stack')

            if (title != "" and description != "" and stack != "") and request.user.mentor.project_set.all().count() < 3:
                new_project = Project(
                    title=title, description=description, stack=stack)
                new_project.mentor = request.user.mentor
                if Project.objects.all().count() < 10:
                    new_project.code = 'PSOC0' + \
                        str(Project.objects.all().count())
                else:
                    new_project.code = 'PSOC' + \
                        str(Project.objects.all().count())
                new_project.save()
            else:
                return HttpResponse("Can only add 3 projects")
            return HttpResponseRedirect(reverse('mentors:dashboard'))
        else:
            return HttpResponse('You are not a mentor.')


class EditProject(View):
    template_name = 'mentors/edit_project.html'

    def get(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentor'):
            project = Project.objects.get(pk=kwargs['pk'])
            return render(request, 'mentors/edit_project.html', {"project": project})
        else:
            return HttpResponse("You are not a mentor")

    def post(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentor'):
            title = request.POST.get('title')
            description = request.POST.get('description')
            stack = request.POST.get('stack')
            project = Project.objects.get(pk=kwargs['pk'])

            if (title != "" and description != "" and stack != "") and request.user.mentor == project.mentor:
                project.title = title
                project.description = description
                project.stack = stack
                project.save()
                return HttpResponseRedirect(reverse('mentors:details', args=(project.id,)))
            else:
                return HttpResponse("Can only add 3 projects")
            return HttpResponseRedirect(reverse('mentors:dashboard'))
        else:
            return HttpResponse('You are not a mentor.')


class Terms(View):
    template_name = 'mentors/terms.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'mentors/terms.html')


class ProjectDetails(View):
    template_name = 'mentors/detail.html'
    is_mentee = False
    is_mentor = False
    is_max_count_not_reached = True
    already_applied = False
    proposal_list = {}

    def get(self, request, *args, **kwargs):
        project = Project.objects.get(pk=kwargs['pk'])

        if hasattr(request.user, 'mentor'):

            if (project.mentor == request.user.mentor):
                self.is_mentor = True
                for proposal in project.proposal_set.all():
                    self.proposal_list[proposal.mentee.user.username] = proposal.proposal_link
            print("ss", self.is_mentor)
            return render(request, self.template_name, {'project': project, 'is_mentee': self.is_mentee, 'is_mentor': self.is_mentor, 'not_reached': self.is_max_count_not_reached, 'already_applied': self.already_applied, 'proposals': self.proposal_list})
        else:

mentors/templates/mentors/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
      /* preloaderL */

      #preloader {
        width: 100%;
        height: 100vh;
        position: fixed;
        background: white
          url('{% static "mentors/img/spinner-preloader.gif" %}') no-repeat
          center;
        z-index: 9999;
      }
    </style>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=UA-168192058-1"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "UA-168192058-1");

      var TxtType = function (el, toRotate, period) {
        this.toRotate = toRotate;
        this.el = el;
        this.loopNum = 0;
        this.period = parseInt(period, 10) || 2000;
        this.txt = "";
        this.tick();
        this.isDeleting = false;
      };

      TxtType.prototype.tick = function () {
        var i = this.loopNum % this.toRotate.length;
        var fullTxt = this.toRotate[i];

        if (this.isDeleting) {
          this.txt = fullTxt.substring(0, this.txt.length - 1);
        } else {
          this.txt = fullTxt.substring(0, this.txt.length + 1);
        }

        this.el.innerHTML = '<span class="wrap">' + this.txt + "</span>";

        var that = this;
        var delta = 200 - Math.random() * 100;

        if (this.isDeleting) {
          delta /= 2;
        }

        if (!this.isDeleting && this.txt === fullTxt) {
          delta = this.period;
          this.isDeleting = true;
        } else if (this.isDeleting && this.txt === "") {
          this.isDeleting = false;
          this.loopNum++;
          delta = 500;
        }

        setTimeout(function () {
          that.tick();
        }, delta);
      };

      window.onload = function () {
        var elements = document.getElementsByClassName("typewrite");
        for (var i = 0; i < elements.length; i++) {
          var toRotate = elements[i].getAttribute("data-type");
          var period = elements[i].getAttribute("data-period");
          if (toRotate) {
            new TxtType(elements[i], JSON.parse(toRotate), period);
          }
        }
        // INJECT CSS
        var css = document.createElement("style");
        css.type = "text/css";
        css.innerHTML = ".typewrite > .wrap { border-right: 0.08em solid #fff}";
        document.body.appendChild(css);
      };
    </script>

    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="{% static 'mentors/fontawesome-free-5.13.0-web/css/all.css' %}"
      rel="stylesheet"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="{% static 'mentors/bootstrap4/css/bootstrap.min.css' %}"
    />

    <!-- Custom CSS-->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'mentors/style.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'mentors/css/base.css' %}"
    />

    <title>PClub Summer of Code</title>
    <link rel="icon" href="{% static 'mentors/img/Pclub-Hex-White.png' %}" />
  </head>

  <body onload="preloaderfunction()">
    <div id="preloader"></div>

    <header>
      <div class="bottomHeader">
        <div class="container-fluid">
          <nav
            class="navbar navbar-dark navbar-expand-md"
            style="background-color: #004d80"
          >
            <a href="{% url 'main_page' %}" class="navbar-brand">
              <img
                src="{% static 'mentors/img/pclub-logo-white.png' %}"
                alt="pclub-logo"
                width="105px"
              />
            </a>
            <button
              data-toggle="collapse"
              data-target="#navbar-Toggler"
              type="button"
              class="navbar-toggler"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar-Toggler">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'main_page' %}">Home</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'projects:project_index' %}"
                    >Projects</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'projects:psoc2020' %}"
                    >PSOC 2020</a
                  >
                </li>
                {% if user.is_authenticated %} {% if user.mentor %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'mentors:dashboard' %}"
                    >Dashboard</a
                  >
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'mentees:dashboard' %}"
                    >Dashboard</a
                  >
                </li>

                {% endif %} {% endif %}
              </ul>
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'mentors:profile' %}"
                    >{{ user.username }}</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'projects:conduct'%}"
                    >Conduct</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'projects:conduct'%}"
                    >Conduct</a
                  >
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#contact">Contact Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user_login'%}">login</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </header>
    {% block body_block %} {% endblock %}

    <footer class="full-footer">
      <a name="contact"></a>
      <div class="container top-footer p-md-3 p-1">
        <div class="row">
          <div class="col-md-6">
            <div class="col-md-8 pl-4 pr-4">
              <img
                class="img-fluid"
                src="{% static 'mentors/img/pclub-logo-white.png' %}"
                alt="logo"
              />
              <p>
                Programming Club UIET or PCIub for short is a student driven
                society that aims af educating students about various domains of
                Computer Science, Electronics and Technology.
              </p>
              <br /><a href="#" class="move-top">Move to top</a><br />
              <p class="social">
                <a
                  class="p-1"
                  href="https://www.facebook.com/pclubuiet"
                  target="_blank"
                  ><i class="fab fa-2x fa-facebook-square"></i
                ></a>
                <a
                  class="p-1"
                  href="https://www.instagram.com/pclubuiet/"
                  target="_blank"
                  ><i class="fab fa-2x fa-instagram-square"></i
                ></a>
                <a
                  class="p-1"
                  href="https://twitter.com/pclubuiet/"
                  target="_blank"
                  ><i class="fab fa-2x fa-twitter-square"></i
                ></a>
                <a
                  class="p-1"
                  href="https://github.com/pclubuiet/"
                  target="_blank"
                  ><i class="fab fa-2x fa-github-square"></i
                ></a>
              </p>
            </div>
          </div>
          <div class="col-md-2"></div>
          <div class="col-md-4 contact">
            <h3>Contact Us</h3>
            <a class="p-1" href="mailto: pclubsummerofcode@gmail.com"
              ><i class="fas fa-envelope mr-1"></i
              >pclubsummerofcode@gmail.com</a
            ><br />
            <a class="p-1" href="mailto: pclubuiet@gmail.com"
              ><i class="fas fa-envelope mr-1"></i>pclubuiet@gmail.com</a
            ><br />
            <br />
            <div class="embed-responsive embed-responsive-16by9">
              <iframe
                class="embed-responsive-item"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3428.9194909558046!2d76.75453041497592!3d30.748762881631613!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ffb15766ff70d%3A0xf6cfa1be358bbc88!2sUniversity%20Institute%20Of%20Engineering%20and%20Technology%2C%20Panjab%20University!5e0!3m2!1sen!2sin!4v1588602306657!5m2!1sen!2sin"
                frameborder="0"
                width="50px"
              ></iframe>
            </div>
          </div>
          <div class="col-md-2"></div>
        </div>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'mentors/bootstrap4/js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'mentors/bootstrap4/js/popper.min.js' %}"></script>
    <script src="{% static 'mentors/bootstrap4/js/bootstrap.min.js' %}"></script>

    <script>
      // preloader
      var preloader = document.getElementById("preloader");

      function preloaderfunction() {
        preloader.style.display = "none";
      }
    </script>
  </body>
</html>

mentors/templates/mentors/create_project.html
{% extends 'mentors/base.html' %} {% load static %} {% block body_block%}
<link rel="stylesheet" href="{% static 'mentors/css/base.css' %}" />
<link rel="stylesheet" href="{% static 'mentors/css/create-project.css' %}" />
    <div class = "section">
        <div class="container">
            <div class="descrip-head">
                <h1>Create Project</h1>
            </div>
            <div class="row justify-content-center">
                <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <div class="form-input">
                        <label>Title :</label>
                        <input type="text" name="title" placeholder="Title of Project"
                        required="required" autocomplete="off">
                    </div>
                    <div class="form-input">
                        <label>Desciption :</label>
                        <textarea type="text" name="description" cols="60" rows="10" required="required" id="id_description" placeholder="Description of Your Project"></textarea>
                    </div>
                    <div class="form-input">
                        <label>Stack :</label>
                        <input type="text" name="stack" placeholder="Stack Used"
                        required="required" autocomplete="off">
                    </div>
                    <input type="submit" name="" value="Create" class="submit btn-primary">
                    <button type="button"><a href="{% url 'mentors:dashboard' %}" class="btn-primary">Cancel</a></button>
                </form>
                <div class="img-bg">
                    <img src="{% static 'mentors/img/project-2.png' %}">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mentors/templates/mentors/dashboard.html
{% extends 'mentors/base.html' %} {% load static %} {% block body_block %}
<link rel="stylesheet" href="{% static 'mentors/css/base.css' %}" />
<link rel="stylesheet" href="{% static 'mentors/css/style.css' %}" />
<section class="home-section pt-4 pb-5">
  <div class="container">
    <div class="row" style="margin-top: 30px">
      {% for project in user.mentor.project_set.all %}

      <div class="col-lg-4 col-md-12 justify-content-center mb-5">
        <div class="card shadow">
          <div class="inner">
            <img
              src="{% static 'mentors/img/card1.jpg' %}"
              class="card-img-top"
              alt="..."
            />
          </div>
          <div class="card-body text-center" style="color: black">
            <h5 class="card-title">{{ project.title }}</h5>
            <p class="card-text">
              {{ project.description|slice:":100"|add:" ..." }}
            </p>
            <p class="card-text">
              Status: {% if project.is_approved %}Approved{% else %}Pending for
              Approval{% endif %}
            </p>
            <a
              href="{% url 'mentors:details' project.id %}"
              class="btn btn-success"
              >Read More</a
            >

            <div class="card-text">
              <p>Selected Students:</p>
              {% for student in project.selected_mentee.all %}
              <p>{{ student.user.username }}</p>
              {% endfor %}
            </div>
            <div class="card-text">
              <p>Applicants:</p>
              {% for student in project.mentee_applications.all %} {% if
              student.selected == NULL %}
              <form method="post" action="{% url 'mentors:dashboard' %}">
                {% csrf_token %}
                <p>{{ student.user.username }}</p>
                <input
                  name="project"
                  value="{{ project.id }}"
                  style="display: none"
                />
                <input
                  name="mentee_id"
                  value="{{ student.id }}"
                  style="display: none"
                />
                <input type="submit" value="Accept Application" />
              </form>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% if show_button %}
  <div class="create-project">
    <button type="button">
      <a href="{% url 'mentors:create_project' %}" class="btn btn-primary"
        >Create new project</a
      >
    </button>
  </div>
  {% endif %}
</section>
{% endblock %}

mentors/templates/mentors/detail.html
{% extends 'mentors/base.html' %} {% load static %} {% load getvaluefromdict %} {% block body_block %}
<link rel="stylesheet" href="{% static 'mentors/css/base.css' %}" />
<link rel="stylesheet" href="{% static 'mentors/css/detail.css' %}" />
    <div class="container">
        <div class="detail-section">            
                <div class="proj-title">
                    <h1>{{ project.title }}</h1>
                    {% comment %} <hr> {% endcomment %}
                </div>
                <hr class="header-hr">
                <div class="mentor">
                    <h6>Mentor: {{ project.mentor.name }}</h6>
                    <div class="mentor-email">
                        <h6>Email: {{ project.mentor.user.email }}</h6>
                        {% comment %} <hr> {% endcomment %}
                    </div>
                    {% comment %} <hr> {% endcomment %}
                </div>
                {% comment %} <hr class="header-hr"> {% endcomment %}
                <div class="description">
                    <h6>Description:</h6>
                    <p>{{ project.description }}</p>
                    <hr>
                </div>
                <div class="stack"> 
                    <h6>Stack Used: <span>{{ project.stack }}</span></h6>
                </div>
                <a href="{% url 'mentors:edit_project' project.id %}" style="padding-left:0.5rem;">Edit the project</a>                
                

                {% if is_mentor %}
                <div class="students">
                <div class="card-text selected-list">
                    <p class="app-head">Selected Students:</p>
                    {% for student in project.selected_mentee.all %}
                    <div class="student">
                        <p>{{ student.user.username }}</p>
                        <p><a href='{{ proposals|get_item:student.user.username }}'>Proposal Link</a></p>
                    </div>
                    {% endfor %}
                  </div>
                  <div class="card-text applicant-list">
                    <p class="select-head">Applicants:</p>
                    {% for student in project.mentee_applications.all %}
                    <div class="student">	
                        <div class="app-detail">
                            <p>{{ student.user.username }}</p>
                            <p><a href='{{ proposals|get_item:student.user.username }}'>Proposal Link</a></p>
                        </div>
                    </div>
                    {% endfor %}
                  </div>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}