mentees/urls.py
from django.urls import path
from . import views

app_name='mentees'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('dashboard/', views.DashBoard.as_view(), name='dashboard'),
     path('profile/', views.Profile.as_view(), name='profile'),
]

mentors/urls.py
from django.urls import path
from . import views

app_name = 'mentors'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('dashboard/', views.DashBoard.as_view(), name='dashboard'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('dashboard/project/new',
         views.CreateProject.as_view(), name='create_project'),
    path('dashboard/project/edit/<int:pk>',
         views.EditProject.as_view(), name='edit_project'),
    path('<int:pk>/', views.ProjectDetails.as_view(), name='details'),
]

projects/urls.py
from django.urls import path
from . import views

app_name='projects'

urlpatterns = [
    path('index/', views.Index.as_view(), name='project_index'),
    path('<int:pk>/', views.ProjectDetail.as_view(), name='detail'),
    path('code_of_conduct/', views.conduct, name='conduct'),
    path('psoc2020/', views.psoc2020, name='psoc2020'),
]

soc/urls.py
from django.contrib import admin
from django.urls import path, include

import projects.views as project_views
import mentors.views as mentor_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', project_views.Main.as_view(), name='main_page'),
    path('adminpanel/', project_views.AdminIndex.as_view(), name='admin_panel'),
    path('adminpanel/<int:pk>/', project_views.AdminProjectDetail.as_view(),
         name='admin_panel_project_detail'),
    path('login/', mentor_views.Login.as_view(), name='user_login'),
    path('logout/', mentor_views.LogOut.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('mentors/', include('mentors.urls')),
    path('projects/', include('projects.urls')),
    path('mentees/', include('mentees.urls')),
    path('terms', mentor_views.Terms.as_view(), name='terms')
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mentees/models.py
from django.db import models
from django.contrib.auth.models import User

from projects.models import Project

#model class for mentee
class Mentee(models.Model):
    name = models.CharField(max_length=64, default=0)
    organization = models.CharField(max_length=64, default=0)
    phone = models.IntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_mentor = models.BooleanField(default=False)
    projects = models.ManyToManyField(Project, related_name='mentee_applications')
    selected = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, related_name='selected_mentee')

    def __str__(self):
        return self.user.username

class Proposal(models.Model):
    mentee = models.ForeignKey(Mentee, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    proposal_link = models.CharField(max_length=200, default='')

mentees/forms.py
from django.forms import ModelForm, CharField, PasswordInput 

from .models import Mentee

class MenteeForm(ModelForm):
    class Meta():
        model = Mentee
        fields = ['name', 'phone', 'organization']

mentees/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import User, Mentee
from projects.models import Project
from mentors.forms import UserForm
from .forms import MenteeForm


#view for handling the registrations form for mentee.
class Register(View):
    form_class = UserForm
    registered = False
    template_name = 'mentees/register.html'
    
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form, 'registered': self.registered})

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()
            
            mentee = Mentee(user=user)
            mentee.save()

            self.registered = True
        else:
            print(form.errors)
        return render(request, self.template_name, {'form': form, 'registered': self.registered})


#view for handling the dashboard for mentee.
class DashBoard(View):
    template_name = 'mentees/dashboard.html'
    show_button = True

    def get(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentee'):
            if request.user.mentee.projects.all().count()>=3:
                self.show_button = False
            return render(request, 'mentees/dashboard.html', {'show_button': self.show_button})
        else:
            return HttpResponse("You are not a mentee")

        
#view to handle profile section of mentee
class Profile(View):
    template_name = 'mentees/profile.html'
    form_class = MenteeForm

    def get(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentee'):
            mentee = request.user.mentee
            if mentee.name==0 or mentee.phone==0 or mentee.organization==0:
                form = self.form_class()
            else:
                form = self.form_class(instance=mentee)
            return render(request, 'mentees/profile.html', {'form': form})
        else:
            return HttpResponse("You are not a mentee.")

    def post(self, request, *args, **kwargs):
        if hasattr(request.user, 'mentee'):
            mentee = request.user.mentee
            form = self.form_class(request.POST, instance=mentee)
            if form.is_valid:
                form.save()
            else:
                print(form.errors)
            return HttpResponseRedirect(reverse('mentees:dashboard'))
        else:
            return HttpResponse("You are not a mentee.")

mentees/templates/mentees/dashboard.html
{% extends 'mentors/base.html' %} {% load static %} {% block body_block %}
<link rel="stylesheet" href="{% static 'mentors/css/base.css' %}" />
<link rel="stylesheet" href="{% static 'mentors/css/style.css' %}" />
<section class="home-section pt-4 ">
    {% comment %} <div class="create-project"> {% endcomment %}
    <div class="container">
        <div class="row">
          {% for project in user.mentee.projects.all %}
      
          <div class="col-lg-4 col-md-12 justify-content-center mb-1">
            <div class="card shadow">
              <div class="inner">
                <img
                  src="{% static 'mentors/img/card1.jpg' %}"
                  class="card-img-top"
                  alt="..."
                />
              </div>
              <div class="card-body text-center" style="color: black;">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">
                  {{ project.description|slice:":100"|add:" ..." }}
                </p>
                <p class="card-text">
                  Status: {% if user.mentee.selected == project %}Selected{% else %}Proposal Under Review{% endif %}
                </p>
                <a href="{% url 'projects:detail' project.id %}" class="btn btn-success">Read More</a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="reference">
          <p>You can refer <a href="https://www.youtube.com/watch?v=929VTAFi9EI&feature=youtu.be">how to make a proposal</a></p>
          <p>Here is an <a href="https://drive.google.com/file/d/1KxZV0PYFql7nFsjjadY-x7vOwcKHgmwz/view?usp=drivesdk">Example Proposal</a></p>
        </div>
      </div>
    {% comment %} </div> {% endcomment %}

    {% if show_button %}
    <div class="create-project">
    <button type="button">
        <a href="{% url 'projects:project_index' %}" class="btn btn-primary">Apply for project</a>
    </button>
    </div>

    {% endif %}
</section>
{% endblock %}

mentees/templates/mentees/profile.html
{% extends "mentors/base.html" %}
{% block body_block %}
<section class="home-section pt-4 pb-5">
<div class='container'>
    <div class='jumbotron'>
        <form action="{% url 'mentors:profile' %}" method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class='create-form-buttons'>
                <input type='submit' value='Submit'>
                <a href="{% url 'mentors:dashboard' %}"><button type='button'>Cancel</button></a>
            </div>
        </form>
    </div>
</div>
</section>
{% endblock %}

mentees/templates/mentees/register.html
{% extends "mentors/base.html" %} {% load static %} {% block body_block %}
<link rel="stylesheet" href="{% static 'mentors/css/style-sign-up.css' %}" />
<link rel="stylesheet" href="{% static 'mentors/css/base.css' %}" />
    <div class = "container mt-3 mb-4">
        {% if registered %}
        <div class='container registered pt-5'>
            <h1>Thank you for registering!</h1>
            <a href="{% url 'user_login' %}" class="btn btn-primary">Login</a>
        </div>
        {% else %}
        <div class="row">
            <div class="mentor-descrip pt-5 pb-5 col-lg-6">
                <h1>After Registering Mentee should proceed as follows -</h1>
                <ul>
                    <li>After loging in Check for the projects in Projects Section and chooses the one you are interested in.</li>
                    <li>Mentee can select upto 3 projects of his/her like and submit proposals for the same. </li>
                    <li>Mentee should submit the public link of the pdf while submitting for a project.</li>
                    <li>The status of the proposals submitted can be viewed in the Dashboard.</li>
                    <li>If a proposal gets accepted, the application will automatically be removed from other projects.</li>
                    <li>For any queries, reach out to us at <a href="mailto: pclubuiet@gmail.com">pclubuiet@gmail.com</a></li>
                </ul>
            </div>
            <div class="signup-form pt-5 pb-5 ">
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <h2>Sign Up as Mentee</h2>
                <p>Please fill in this form to create an account!</p>
                <hr />
                <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon p-2"><i class="fa fa-user"></i></span>
                    <input
                    type="text"
                    class="form-control"
                    name="username"
                    placeholder="Username"
                    required="required"
                    />
                </div>
                </div>
                <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon p-2"
                    ><i class="fa fa-paper-plane"></i
                    ></span>
                    <input
                    type="email"
                    class="form-control"
                    name="email"
                    placeholder="Email Address"
                    required="required"
                    />
                </div>
                </div>
                <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon p-2"><i class="fa fa-lock"></i></span>
                    <input
                    type="password"
                    class="form-control"
                    id="password"
                    name="password"
                    placeholder="Password"
                    required="required"
                    />
                </div>
                </div>
                <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon p-2">
                    <i class="fa fa-lock"></i>
                    <i class="fa fa-check pt-1"></i>
                    </span>
                    <input
                    type="password"
                    class="form-control"
                    id="confirm_password"
                    name="confirm_password"
                    placeholder="Confirm Password"
                    required="required"
                    />
                </div>
                </div>
                <div class="form-group checkbox-form">
                <label class="checkbox-inline p-"
                    ><input type="checkbox" required="required" /> I accept the
                    <a href="#">Terms of Use</a> &amp;
                    <a href="#">Privacy Policy</a></label
                >
                </div>
                <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
                </div>
            </form>
            <div class="text-center">
                Already have an account? <a href="{% url 'user_login' %}">Login here</a>
            </div>
        </div>
    </div>
    {% endif %}
</div>
<script>
    var password = document.getElementById("password")
  , confirm_password = document.getElementById("confirm_password");

    function validatePassword(){
    if(password.value != confirm_password.value) {
        confirm_password.setCustomValidity("Passwords Don't Match");
    } else {
        confirm_password.setCustomValidity('');
    }
    }

    password.onchange = validatePassword;
    confirm_password.onkeyup = validatePassword;
</script>
{% endblock %}